spring:
  shardingsphere:
    dataSource1:
      name: dataSource1
      driver-class-name: org.postgresql.Driver
      url:  jdbc:postgresql:xxxx
      username: ${username}
      password: ${password}
      max-life-time: 30000
      connection-timeout: 20000
    dataSource2:
      name: dataSource1
      driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
      url: jdbc:sqlserver:xxxx
      username: ${username}
      password: ${password}
    props:
      sql-show: false