spring.datasource.url=jdbc:postgresql://${PGHOST}:${PGPORT}/${PGDATABASE}?sslmode=require
spring.datasource.username=${MANAGED_IDENTITY_NAME}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.cloud.azure.credential.managed-identity-enabled=true
spring.datasource.azure.passwordless-enabled=true
spring.cloud.azure.profile.cloud-type=${CLOUD_TYPE:AZURE}

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
