# 1. The "azure.scopes" parameter is required only when BOTH of the following conditions are satisfied:
#   - The Azure environment is NOT Azure Public (i.e., it's Azure China, Azure Germany, or Azure Government).
#   - The Spring Cloud Azure version used in the project does not include the fix for this bug: https://github.com/Azure/azure-sdk-for-java/issues/47096
# 2. All valid values for "azure.scopes" are here:
#   - AZURE_PUBLIC_CLOUD: https://ossrdbms-aad.database.windows.net/.default
#   - AZURE_CHINA: https://ossrdbms-aad.database.chinacloudapi.cn/.default
#   - AZURE_GERMANY: https://ossrdbms-aad.database.cloudapi.de/.default
#   - AZURE_GOVERNMENT: https://ossrdbms-aad.database.usgovcloudapi.net/.default
spring.datasource.url=jdbc:postgresql://${PGHOST}:${PGPORT}/${PGDATABASE}?sslmode=require
# the username of datasource SHOULD be the name of managed identity
spring.datasource.username=${MANAGED_IDENTITY_NAME}
spring.datasource.driver-class-name=org.postgresql.Driver

# Enable Azure managed identity passwordless authentication
spring.datasource.azure.passwordless-enabled=true
spring.cloud.azure.credential.managed-identity-enabled=true

# Supported types are: AZURE, AZURE_CHINA, AZURE_US_GOVERNMENT, OTHER. The default value is AZURE.
spring.cloud.azure.profile.cloud-type=${CLOUD_TYPE:AZURE}

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
