url=jdbc:sqlserver://<db_server_name>.database.windows.net:1433;databaseName=<db_name>;msiClientId=<client_id>;authentication=ActiveDirectoryMSI;
user=demo@$AZ_DATABASE_NAME
password=$AZ_SQL_SERVER_PASSWORD

##placeholder for mi